_target_: src.datamodules.musical_features_datamodule.MusicalFeaturesDataModule
data_dir: ${paths.data_dir}

batch_size: 128

train_val_test_split: [ 0.9, 0.07, 0.03 ]

num_workers: 0
pin_memory: False
